const routes = {
    login: "/",
    admin: "/admin",
    adminSemesters: "/admin/semesters",
    adminSubjects: "/admin/subjects",
    adminPhases: "/admin/phases",
    adminUsers: "/admin/users",
    adminCourses: "/admin/courses",
    adminRooms: "/admin/rooms",
    adminExaminers: "/admin/examiners",
    adminSlots: "/admin/slots",
    staff: "/staff",
    staffExaminer: "/staff/examiners",
    staffExamPhase: "/staff/examPhase",
    staffExamSlot: "/staff/examSlot/:id",
    staffExamSlotDetail: "/staff/examSlotDetail/:id",
    staffVolunteers: "/staff/volunteers",
    lecturer: "/lecturer",
    lecturerRegister: "/lecturer/register/:id",
    lecturerExamSlots: "/lecturer/examSlots",
    lecturerSchedule: "/lecturer/schedule",
    pageNotFound: "/*",
    adminTest: "/admin/test",
    student: "/student",
    studentExamSlots: "/student/examSlot",
    studentSchedule: "/student/schedule",
};

export default routes;
